version: '3'
services:
  openresty:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "33333:80"
    volumes:
      - ./example/conf:/usr/local/openresty/nginx/conf
      - ./example/conf.d:/etc/nginx/conf.d
